# Generated by Django 4.1 on 2023-01-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OriginALevel_app', '0003_rename_user_originalevel_replymodel_replied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalevel_replymodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='OriginALevel_app.originalevel_postmodel'),
        ),
    ]
