# Generated by Django 4.1 on 2023-02-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OriginALevel_app', '0005_rename_user_originalevel_postmodel_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='originalevel_ratingmodel',
            old_name='_rating',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='originalevel_ratingmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='OriginALevel_app.originalevel_postmodel'),
        ),
    ]
